### ISSUE TITLE
New config window does not save its settings

### ISSUE THREAD

**Issue by MsgLosers** [NightLancer/PixivPreview#11] opened 2020-04-03 12:47 UTC
~~hey, sorry but it looks like i cant get the new settings window to save its changes. it also does not seem to appear on regular manga/post-pages now.~~

edit: never mind. it took a few tries and refreshes but eventually it saved the changes!

so the only remaining issue: config does not open from mange/post-pages

**Comment by NightLancer** [comment] 2020-04-03 12:54
Hello. Can you specify your locale and one manga and one single post page where it is not working? I've tried to open illust page just now with Chinese simplified(as I guess) and it worked fine...

**Comment by NightLancer** [comment] 2020-04-03 14:50
@MsgLosers I've made some other update. With a little luck, maybe this will solve your problem?)

And I would be glad to know, if my highlighting feature works at all in localizations except English? It seems it wasn't, and whole this time I didn't even know that, 'cause I've used only english... =\

There must be result such like this:
![image](https://user-images.githubusercontent.com/19971564/78373650-8a79aa80-75d3-11ea-831a-686e0ae2373a.png)

**Comment by NightLancer** [comment] 2020-04-07 23:26
@MsgLosers Hello. I realize that 4 days is not quite a decent period of time, and you might have your own things to do, but I'm just reminding — is this problem still exists? Maybe it was temporary bug?..

**Comment by NightLancer** [comment] 2020-04-20 21:14
@MsgLosers Hi. Is everything okay? Either all works good, and you just forgot about this post, or... 

I've made some other update, to fix possible bug with not saving preferences if menu is currently opened in other tab. Now it will close and apply immediately after clicking on any space(including clicking on links to open new tabs), so I hope it would be enough to prevent such errors.

Hope you're doing well.

**Comment by MsgLosers** [comment] 2020-05-09 15:10
@NightLancer hey, I apologize. I did completely forget about the issue until today. (If only I had notifications enabled...) Life is turbulent, but that is no excuse. I completely forgot and had reminders and notifications turned off.

I am so sorry.

I checked again now and here is the results:
**Version 2.33***

✅ Works from all pages that I tested (!)

1. Front pages (after clearing old browser cache, browser issue):
https://www.pixiv.net/en/
https://www.pixiv.net/en/?utm_source=pixiv&utm_medium=header&utm_campaign=service_grid_menu
2. Post page
3. Manga page
4. Profile page
5. Artists profiles (all tabs)


Thank you! :) ❤️ 

Also yes I have noticed the highlight. This currently only appears on my profile's bookmarks (the title of the creators' art is highlighted).

Previously I remember seeing this a lot in search and on front pages, but now it seems I can only find it on my bookmarks. This is fine since I use my own third party method to highlight to my specific needs. :)


I am doing well, thankfully. I hope you are well and healthy too!

**Comment by NightLancer** [comment] 2020-05-10 00:02
@MsgLosers hello. No problems) [It was just a little strange that I've answered after 7 minutes and had no response at for so long (I have my notifications on)].

Just glad to hear that settings menu is working well for you!)

> Also yes I have noticed the highlight. This currently only appears on my profile's bookmarks (the title of the creators' art is highlighted).

Hmm, I'm specifically changed my locale to Chinese to check if it works, and as you may seen on my comment above, it works for "Discovery" as well... But seems this feature is not so critical, since no one have complied to me about that. But still I'll try to expand it to all locales and fix that problems too, if I found them. 

> This is fine since I use my own third party method to highlight to my specific needs. :)

Okay, I've read an editing history of your previous comment(it was somewhat funny :D), and yes, I can simply make an another option to on/off this feature if it somehow interferes with other script you're using. I will stick to my code anyway, but it would be curious to see other's method for solving this, can you get me some name or link? I'm personally started to make such an feature because I haven't found it years ago but had a very great desire for such. 

Anyway, it is good that all is good!

**Comment by MsgLosers** [comment] 2020-05-10 04:24
@NightLancer Sorry for all the edits. 😄 I am almost never happy with my first post and when I start to edit, things quickly escalate out of control with microediting. I also made a mistake as I tested the actual final version and removed some text that I realized was incorrect.

An on-off method for it would be nice (but not necessary! I like your feature, it is very useful, and it does something different than my third party method) 😃 

Sure, no problem! I use an application called Hydrus (hydrus network) and with it a browser extension known as the "hydrus companion". What Hydrus does it allow you to download files from places (for example pixiv) into your own local booru-like database. The hydrus companion then connects with the hydrus API and lets you do stuff like highlight on the website which files you have already downloaded (so you don't download them twice) or show which posts you deleted in the past so you can avoid them while browsing. A very different usecase. :) I'll share the links if you're curious and want to take a look:
`https://hydrusnetwork.github.io/hydrus/
https://gitgud.io/prkc/hydrus-companion/`

**Comment by NightLancer** [comment] 2020-05-11 03:07
@MsgLosers  
> Sorry for all the edits

NP, I'm just saying it was curious to read all of that:) 

> An on-off method for it would be nice (but not necessary! I like your feature, it is very useful, and it does something different than my third party method) smiley

Hah, okay) It is good to hear that this feature is used not only by me :D 
My highlighting feature was intended for recommendation zones(discovery, rankings, suggested works under artwork page) to visualize works of users you're already following(assuming that if you like artist works - you will follow it). And that was exactly for preventing double-viewing of your "feed"(as not everyone checks it every day and remembers it ALL). I'm personally like to watch my artworks of my followed artists on proper page (http://www.pixiv.net/bookmark_new_illust.php), and not to double-check every artist is it followed or not, or have I seen this before or not. Thus even if I come across new work in other section that "bookmark_new_illust", I will ignore it because I know it will be in my "feed". And when I have mood and time for checking my feed - then I watch it all at once. (I don't know how users use this feature, but that's how it was planned to be used).

> download files from places (for example pixiv) into your own local booru-like database. 

Hmm, I was thinking to do an simple database for all viewed images(not only feed) someday. And again it would be different use case)
But I must admit that sometimes I double-check images if I downloaded them or just watched manually... That is not very comfortable and I was vaguely thinking that maybe, when I decide to learn not only js but windows-browser scripting as well, I'll try to do some kind of such a feature. I'm glad to know that such an app is already exist! And if it can load all of my old saved images(they have proper illust id's) - it would be priceless software!
Thank your for such a finding!)

**Closed as completed by NightLancer** 2020-05-11 03:07 UTC
Labels: question, resolved
