### ISSUE TITLE
Suggestion. Fast download for picture

### ISSUE THREAD

**Issue by BonkeyKongz** [NightLancer/PixivPreview#18] opened 2021-11-15 22:59 UTC
Make the control + left click preview download also apply to picture sets like here https://www.pixiv.net/en/artworks/93964680
So user can fast download those images with a click

**Comment by NightLancer** [comment] 2021-11-16 15:57
@BonkeyKongz Hello. There is already a combination of Ctrl+Click to download selected image. 
There is single artwork by that link, I suppose you was intended to link a multiple one? I may try to add Ctrl+Shift+Click for batch downloading, tho I can't guarantee it will work properly on high amounts for every user.

**Comment by BonkeyKongz** [comment] 2021-11-16 16:25
Hello! Well control+click isn't working for me on those kinds of pages, is there a setting I need to enable?

**Comment by NightLancer** [comment] 2021-11-17 02:43
@BonkeyKongz okay, seems things are not clear enough. Are you asking for being able to save art on its own artwork page with same Ctrl+Click option, because there is no preview over the original one and therefore you can't save it with script? If so, that is much simpler request and I definitely can do that.

**Comment by NightLancer** [comment] 2021-11-17 02:52
@BonkeyKongz Try new [3.10](https://github.com/NightLancer/PixivPreview/raw/master/PixivPreview.user.js) version, now it is possible to download originals with Ctrl+LMB on the own artwork page as well. Works for multiple images as well, both full-screened and default layouts. I hope that is what you was asking for)

**Comment by NightLancer** [comment] 2021-11-24 01:22
@BonkeyKongz so, does your request fulfilled and now you can download images from artwork page? It works fully at my side. 
I'm closing this issue but you can still comment here about results.

**Closed as completed by NightLancer** 2021-11-24 01:22 UTC
Labels: enhancement, resolved
