### ISSUE TITLE
Preview displays too fast

### ISSUE THREAD

**Issue by MsgLosers** [NightLancer/PixivPreview#4] opened 2018-11-01 13:43 UTC
The mouse-hover preview is too fast. You cannot move mouse across screen without starting a preview; this gets in the way of regular pixiv-browsing. Perhaps could we get an option to have a delay on the hover? "if mouse-hover on thumbnail for [X] ms then show preview"

alternatively I would also prefer to left-mouse click each thumbnail to first get the preview and then click again/click "visit page" button inside preview to go to the post

Anyway the way previews show up immediately is something I think needs fixing. If you move mouse too fast or scroll down on the page, the preview get glitchy and stuck in a permanent-open state.

Tampermonkey for Chrome, script version 1.32.2

**Comment by NightLancer** [comment] 2018-11-01 21:06
@MsgLosers When I was writing my script I had the purpose to get maximum efficiency with minimal user interaction(without extra clicks and new page openings as much as possible). There was proposal to add a timeout before showing a preview, but since rapid mouse moving across page will cause those timers to start and stop continuously(which will probably cause extra impact on the CPU and surely cause a much of pain to handle all of that timers), I've decided not to use them(at least until I find out how to optimize it).

But I can make an option to show preview when clicking on image instead of hovering it, wait for an update. 
BTW, You can go to the image post by clicking MMB on its preview(single click is reserved to open an original in new tab) in current version of script.

**Comment by NightLancer** [comment] 2018-11-01 21:44
@MsgLosers done, update to [1.32.3](https://greasyfork.org/scripts/39387-pixiv-arts-preview-followed-atrists-coloring/code/Pixiv%20Arts%20Preview%20%20Followed%20Atrists%20Coloring.user.js).
Set ` PREVIEW_ON_CLICK = true; ` in script code after updating to change preview condition to LMB-click.

**Comment by NightLancer** [comment] 2018-11-03 09:36
@MsgLosers The problem is solved? If there are no additions, I will close this issue in a week.

**Comment by MsgLosers** [comment] 2018-11-04 13:25
Hey @NightLancer thanks for the feedback & update! I will check it out right now and update this comment!
EDIT: It works flawlessly and perfectly the way I hoped it would! Thank you so much for taking the time and effort. I'm having a much better time and experience with using this script now! Cannot thank you enough!

Sidenote: As for the timer-trouble, perhaps it'd be better for the CPU to run a single timer and reset it every time the mouse target changes? Or did you try that as well and experienced the same issue with CPU load?

**Comment by NightLancer** [comment] 2018-11-04 20:27
Hello @MsgLosers. I tried to add timer and this time everything went more smoothly than last time. CPU usage was on a par with multiple occasional preview showing case.

To add the preview appearing delay, change `DELAY_BEFORE_PREVIEW = 0;` from 0 to desired value in ms (1000 = 1 second). [`DELAY_BEFORE_PREVIEW = 1000;` , аs for example].

Note that for now you must reset this setting next time you'll update script, but I think I will add settings storing feature in the future.

Also note that this settings currently aren't foolprof, so if you set both `PREVIEW_ON_CLICK = true;`  and ` `DELAY_BEFORE_PREVIEW = 1000;`, you'll receive delay before preview after clicking as well=)

**Comment by MsgLosers** [comment] 2018-11-11 00:23
Hi @NightLancer thanks for the update! I notice the setting had reset; but it wasn't / isn't a problem. I'm very happy you had a better experience with this "delayed loading" setting the second time around! 👍  I haven't been able to try it, as I much rather prefer the click-to-preview method as I mentioned (and honestly, I easily forget to test-and-feedback). 😄

**Comment by NightLancer** [comment] 2018-11-11 07:08
@MsgLosers glad to hear that resetting preview option wasn't a problem) 
I think current issue is solved and we can close it.

**Closed as completed** 2018-11-11 07:08 UTC
Labels: enhancement, resolved
